version: '3'

services:
    php:
        image: php:7.4-apache
        container_name: php
        ports:
            - 80:80
        privileged: true
        volumes:
            - ./php/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
            - ./php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./php/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf:ro
            - ./php/laravel:/var/www/html
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: docker-database
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            TZ: 'Asia/Tokyo'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
            - ./mysql/init:/docker-entrypoint-initdb.d
            - ./mysql/data:/var/lib/mysql
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.8
        container_name: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOSTS=mysql
            - PMA_USER=root
            - PMA_PASSWORD=root
        ports:
            - 8080:80
        depends_on:
            - mysql
